Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -13,12 +13,15 @@ jobs:
         uses: actions/checkout@v2
 
       - name: Display Contents
-        run: cat index.html
+        run: ls -R
+
+      - name: Check if index.html exists
+        run: test -e index.html || echo "File not found"
 
       - name: Deploy to S3
         run: |
-          aws s3 cp ./index.html s3://$BUCKET_S3 --acl public-read
-          echo "AWS CLI Version:"
-          aws --version
-          echo "List S3 Contents:"
-          aws s3 ls s3://$BUCKET_S3/
+          if [ -e "index.html" ]; then
+            aws s3 cp ./index.html s3://$BUCKET_S3 --acl public-read
+          else
+            echo "File not found. Deployment skipped."
+          fi
